version: "3"
services:
  app:
    build:
      context: .
    # command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails assets:precompile && bundle exec rails s -e production"
    volumes:
      - .:/auth0-sample
      - bundle:/usr/local/bundle
      # - public-data:/auth0-sample/public
      # - tmp-data:/auth0-sample/tmp
      - yarn-cache:/usr/local/share/.cache/yarn/v6
    ports:
      - "3000:3000"
      - "8080:8080"
    stdin_open: true
    tty: true
volumes:
  bundle:
  yarn-cache:
  public-data:
  tmp-data:
